plugins {
    id 'com.enonic.xp.app'
    id 'maven-publish'
}

dependencies {
    implementation xplibs.api.script
    include xplibs.portal
    include xplibs.admin
    include xplibs.context
    include "com.enonic.lib:lib-util:3.1.1"
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo()
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = "${group}"
            artifactId = "${projectName}"
            version = "${version}"

            from components.java
        }
    }
}

wrapper {
    gradleVersion = '9.7.1'
    distributionType = Wrapper.DistributionType.BIN
}
